name: Deploy to Vercel

on:
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install Vercel
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --yes