name: Deploy to Vercel

on:
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Deploy backend to Vercel
        working-directory: ./apps/backend
        run: npm install -g vercel
        env:
          VERCEL_TOKEN: ${{ secrets.TOKEN }}
        run: vercel --prod --token $TOKEN --yes

      - name: Deploy frontend to Vercel
        working-directory: ./apps/frontend
        run: npm install -g vercel
        env:
          VERCEL_TOKEN: ${{ secrets.TOKEN }}
        run: vercel --prod --token $TOKEN --yes