name: CI action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Install dependencies for frontend
        working-directory: ./apps/frontend
        run: npm install

      - name: Install dependencies for frontend
        working-directory: ./apps/backend
        run: npm install

      - name: Run the tests for the frontend
        working-directory: ./apps/frontend
        run: npm test

      - name: Run the tests for the backend
        working-directory: ./apps/backend
        run: npm test
